title: Orzlab
baseurl: "" 
url: "https://orz-lab.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/

plugins: [jekyll-feed]

youtube_channel: "https://www.youtube.com/@Orz-lab"
github_org: "https://github.com/orz-lab"
facebook_page: "https://www.facebook.com/orzlab.real"